### ISSUE TITLE
so Hello World fails to compile with no member named 'in_place' in namespace 'std' error

### ISSUE THREAD

**Issue by atraastrum** [eao197/so-5-5#21] opened 2019-01-17 12:39 UTC
I pulled SO and built it with cmake. I use the following cmake file for my project
```
cmake_minimum_required(VERSION 3.13)
project(Experimen-1)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)


add_executable(experiment_1
  main.cpp
)

set(DEP_DIR "/home/my_name/il_dependencies/")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")

SET (sobjectizer_DIR "${DEP_DIR}lib/cmake/sobjectizer" )
find_package( sobjectizer REQUIRED )

target_include_directories( experiment_1 BEFORE PRIVATE "${DEP_DIR}/include" )
target_link_libraries( experiment_1 PRIVATE  sobjectizer::SharedLib )
```   

The code in main is very simple, not even launching environment
```
#include <iostream>
#include <so_5/all.hpp>

int main() {
  std::cout << "Works...\n" ;
}
``` 
When I try to build I get long list of errors. First error message being:
```
In file included from /home/boris/projects/thesis/so5_experiments/experiment-1/m
ain.cpp:3:
In file included from /home/boris/il_dependencies/include/so_5/all.hpp:15:
In file included from /home/boris/il_dependencies/include/so_5/rt/h/rt.hpp:13:
In file included from /home/boris/il_dependencies/include/so_5/rt/h/agent.hpp:30
:
In file included from /home/boris/il_dependencies/include/so_5/rt/h/agent_contex
t.hpp:17:
In file included from /home/boris/il_dependencies/include/so_5/rt/h/agent_tuning
_options.hpp:16:
In file included from /home/boris/il_dependencies/include/so_5/rt/h/message_limi
t.hpp:16:
In file included from /home/boris/il_dependencies/include/so_5/rt/h/enveloped_ms
g.hpp:17:
In file included from /home/boris/il_dependencies/include/so_5/h/optional.hpp:15
:
/home/boris/il_dependencies/include/so_5/3rd_party/optional-lite/nonstd/optional
.hpp:319:12: error:
      no member named 'in_place' in namespace 'std'
using std::in_place;
      ~~~~~^
``` 
I use clang 6 to compile and it support C++17. So it should support std::in_place but code also fails:
```
#include <iostream>
#include <utility>
using std::in_place;

int main() {
  std::cout << "Works...\n" ;
}
```
Might be that there is something wrong with my environment

**Comment by eao197** [comment] 2019-01-17 12:42
Hi!

Can you try to use C++14 standard?

SObjectizer-5.5 is not extensively tested with C++17.

**Comment by atraastrum** [comment] 2019-01-17 12:54
Hello,

It compiles with C++14 and C++11 standards. Thanks a lot.

**Comment by eao197** [comment] 2019-01-17 12:56
Can you tell your OS and exact version of your compiler?

PS. SObjectizer-5.5 uses external projects optional_lite for working with `optional` on old compilers. It seems that version of optional_lite doesn't correctly detect compiler in your case. I want to try to upgrade optional_lite and check it.

**Comment by atraastrum** [comment] 2019-01-17 13:01
Compiler version:  
clang version 6.0.0-1ubuntu2~16.04.1 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

OS Version
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

**Comment by eao197** [comment] 2019-01-17 13:03
Thanks! I will test this combo.

**Comment by eao197** [comment] 2019-01-17 13:45
I have tried to use the latest clang-6.0 for ubuntu-16.04 as described [here](https://blog.kowalczyk.info/article/k/how-to-install-latest-clang-6.0-on-ubuntu-16.04-xenial-wsl.html). I've got clang-6.0.1 instead of clang-6.0.0:
```
eao197@z930:~/sandboxes/so-5.5/dev$ clang++-6.0 --version
clang version 6.0.1-svn334776-1~exp1~20190114064905.115 (branches/release_60)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
I don't get that error with C++17. But may be it is because I also have gcc-7 and gcc-8 on the same machine and clang uses more fresh standard library headers.

**Comment by atraastrum** [comment] 2019-01-17 14:29
I have version 5 installed
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

I was thinking the same, that something is probably wrong with my environment.

**Comment by atraastrum** [comment] 2019-01-30 15:24
@eao197  I was able to reproduce the issue on another virtual machine. Here is video capture if your are interested
https://drive.google.com/open?id=1ZYymrHGLel1DWpVYdeMMN35TUlC29gZG. You need to download the video because the quality is not very good if viewed from browser.

**Comment by eao197** [comment] 2019-01-30 15:29
@atraastrum thanks for providing this info.
I'll try to investigate it further in next couple of days.

**Comment by eao197** [comment] 2019-01-31 09:31
@atraastrum can you tell me how did you install clang-6.0 on your Ubuntu 16.04?

**Comment by atraastrum** [comment] 2019-01-31 13:02
@eao197 I installed it with `apt-get install clang clang-6.0`. After that, I have set clang-6.0 as my default `C` and and `CPP` compilers with:
```
sudo update-alternatives --install /usr/bin/clang clang /usr/lib/llvm-6.0/bin/clang 50
sudo update-alternatives --install /usr/bin/clang++ clang++  /usr/lib/llvm-6.0/bin/clang++ 50
sudo update-alternatives --config cc
sudo update-alternatives --config c++
```
I have the following versions of clang installed 
![image](https://user-images.githubusercontent.com/12462953/52055814-2095e900-2569-11e9-8348-2d0c20c45ebe.png)

**Comment by eao197** [comment] 2019-01-31 13:05
Thanks, I still trying to reproduce that problem. This time with using Docker and fresh image of Ubuntu. I hope your info will help.

**Comment by atraastrum** [comment] 2019-01-31 13:10
I have this problem in VM instance running inside VirtualBox.

**Comment by eao197** [comment] 2019-01-31 13:20
> I have this problem in VM instance running inside VirtualBox.

I don't think it is really matters. At least I hope so.

**Comment by eao197** [comment] 2019-01-31 13:49
I have reproduced that error. https://github.com/eao197/so5_5_github_issue21 -- there is a Dockerfile to create Ubuntu 16.04 with clang-6.0.0 inside.

I will try to find a workaround tomorrow.

**Comment by eao197** [comment] 2019-02-01 10:03
The problem is related to libstd++. By default clang uses stdlib from already installed libstdc++ from GCC. In your case it is rather old libstd++ from gcc-5.4. This version of libstdc++ hasn't proper definition of std::in_place, required for C++17.

So you have several options:

* switch to more modern Ubutnu (any version that ships with gcc-7 would be appropriate);
* install gcc-7 or gcc-8 (instructions you can find [here](https://gist.github.com/jlblancoc/99521194aba975286c80f93e47966dc5) or you can look into [my Dockerfile](https://github.com/eao197/so5_5_github_issue21/blob/master/Dockerfile#L26-L29));
* get, compile and install libc++ from LLVM project. Some instructions you can find [here](https://stackoverflow.com/questions/39332406/install-libc-on-ubuntu).

I think options N1 and N2 are the easiest.

**Comment by atraastrum** [comment] 2019-02-01 11:14
@eao197 Thank you for sorting this out. I will try out solutions you have provided.

**Comment by eao197** [comment] 2019-02-07 15:32
@atraastrum I close this issue. If you still need help on this topic please reopen the issue again.

**Closed as completed by eao197** 2019-02-07 15:32 UTC
